#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE_FILE="${PREPMASTER_PROFILE_FILE:-$REPO_ROOT/config/install-profile.env}"

install_kolibri=0
install_ka_lite=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-only)
      install_kolibri=0
      install_ka_lite=0
      shift
      ;;
    --enable-kolibri)
      install_kolibri=1
      shift
      ;;
    --enable-ka-lite)
      install_ka_lite=1
      shift
      ;;
    --enable-all)
      install_kolibri=1
      install_ka_lite=1
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      echo "Usage: $0 [--base-only] [--enable-kolibri] [--enable-ka-lite] [--enable-all]" >&2
      exit 1
      ;;
  esac
done

cat > "$PROFILE_FILE" <<EOF
# Generated by scripts/select_install_profile.sh
INSTALL_BASE_STACK=1
INSTALL_OPENSTREETMAPS=1
INSTALL_KIWIX=1
INSTALL_KOLIBRI=$install_kolibri
INSTALL_KA_LITE=$install_ka_lite
EOF

echo "Wrote install profile to $PROFILE_FILE"
